### ISSUE TITLE
TypeError on example

### ISSUE THREAD

**Issue by basz** [prooph/micro#12]
`php examples/register_and_change_username.php`

Gives an TypeError. Not sure if that is intentional cause running an InvalidCommand

```
TypeError
"Return value of Prooph\\Common\\Messaging\\DomainMessage::messageName() must be of the type string, null returned"
```

**Comment by prolic** [comment]
This is intended, an example how something fails.

Am 22.01.2017 06:33 schrieb "Bas Kamer" <notifications@github.com>:

**Comment by basz** [comment]
i see. perhaps a comment would make that clearer... me as short attention span noop run example, see error, think 'sjit', run off

**Comment by prolic** [comment]
Then add a comment ;-)

**Comment by basz** [comment]
HAHA
