### ISSUE TITLE
Version vs. event no problem with snapshots

### ISSUE THREAD

**Issue by codeliner** [prooph/micro#13]
We have a larger problem maybe with the new snapshot implementation in general. See this line: https://github.com/prooph/micro/blob/master/src/SnapshotReadModel.php#L79

This is wrong. You cannot query the event position using the version of the aggregate because they are not the same.
We cannot use the aggregate version to query missing events from the event stream.

See here: https://github.com/prooph/micro/blob/master/src/Kernel.php#L81
At the moment information from snapshot store is not used but how can we change that?
We would need to store the event position along with the snapshot but we don't have this information available in the message.

Any ideas @prolic

**Comment by prolic** [comment]
This is just a small bug and a mini enhancement. Before I make longer explanations, I just fix it in a few hours.
