### ISSUE TITLE
add micro command for composer

### ISSUE THREAD

**Issue by prolic** [prooph/micro#21]
# Requirements:

- able to run composer update for a single microservice
- able to run composer install for a single microservice
- able to run composer update for all microservices
- able to run composer install for all microservices

# Example docker-command:

`docker run --rm -it --volume $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK --volume $(pwd):/app --volume $(pwd)/../../packages:/packages prooph/composer:7.1 install`

As you can see, this docker command is quite long and hard to remember, therefore we want to provide shortcuts for micro.

# Things to note:

Each php-service can use a different image and PHP version (f.e. 5.6 on service1 and 7.1 on service2). Therefore the correct prooph/composer images with the same php version has to be chosen correctly by this command.

# Syntax suggestion

`./bin/micro micro:composer:update service1`
`./bin/micro micro:composer:update --all`
`./bin/micro micro:composer:install service2`
`./bin/micro micro:composer:install --all`

**Comment by prolic** [comment]
Another hint: you have to parse the `docker-compose.yml` file and get all services with prooph-php image. Then check if composer.json file exists. The service must be in `./service/<service name>`.

**Comment by oqq** [comment]
@prolic assign me here.

**Comment by codeliner** [comment]
As soon as this feature is merged we should move all cli stuff to a separate repo, see #25
