### ISSUE TITLE
Add pdo env to php images if they are depended

### ISSUE THREAD

**Issue by prolic** [prooph/micro#22]
# Scenario

1) User creates a postgres/mysql database (`./bin/micro micro:setup:postgres`) 
2) User creates a php-service and selects this postgres database as dependend (`./bin/micro micro:setup:php-service`)

# Feature Request

All MySQL and PostgreSQL databases created by micro cli commands, have a label `prooph-pdo:true` in the docker-compose.yml.

When the php-service is created, it should check for the `prooph-pdo` label and add the following environment variables to the php-image:

`PROOPH_PDO_DSN=pgsql:host=postgres port=5432 dbname=micro_do`
`PROOPH_PDO_USER=postgres`
`PROOPH_PDO_PWD=`

with the values of host name, port number, dbname, user & password taken from the docker-compose.yml file

# Goal

In the PHP service you can create a database connection very easy with the given environment variables, so no additonal config is required for this service.

**Comment by sandrokeil** [comment]
We should not write the credentials in the docker-compose.yml file. We should rely on environment variables and the user have to ensure that they are set. This is the production ready way. 

Another way is to use [Docker secrets](https://docs.docker.com/engine/swarm/secrets/). But I guess, the user input for credentials can also be an env variable or a file?

**Comment by codeliner** [comment]
We should keep it simple for now. The skeleton should help developers to get started. Everything that makes the configuration more complex than it should can be moved to documentation. In a production set up you may connect to different database anyway. You have to modify the Docker configuration for production but you can start development without pain. Simplicity is the main goal of this skeleton. Please keep that in mind.

**Comment by bweston92** [comment]
@sandrokeil environment should be fine for getting peoples feet wet. If you wanted to go to the extreme for development purposes we could add Vault using leases and audits. I use environment variables in docker-compose my development as then it is easier to manage.
