### ISSUE TITLE
Remove upstream definition from nginx site config

### ISSUE THREAD

**Issue by sandrokeil** [prooph/micro#29]
The `upstream` definition is only needed to add multiple server for one upstream. But this should be handled by an load balancer who resolves the Docker service name. This is done by Docker Swarm or an AWS Elastic Load Balancer. Does we really need it? But I have to check if the `resolver` definition is needed then, this would be a problem.

**Comment by codeliner** [comment]
Atm the Upstream is used to dynamically Link a php-fpm Container based on http method. Was the only way to get it working, but maybe we find a better way. Just submit a PR

**Comment by sandrokeil** [comment]
This is resolved by this [PR](https://github.com/prooph/micro-do/pull/5) and I've created a new [issue in micro-cli](https://github.com/prooph/micro-cli/issues/5).
