### ISSUE TITLE
Add message validator

### ISSUE THREAD

**Issue by prolic** [prooph/micro#4]
Let's check a message upfront and return early, when it's not confirming to the requirements

**Comment by prolic** [comment]
A provided default function could simply return the message and to nothing

**Comment by prolic** [comment]
Question: Is the really required or should it be up to the user land implementation?

**Comment by codeliner** [comment]
good question, I think it can be userland: use setPayload method of the command f.e. or [JSON Guard](http://json-guard.thephpleague.com/) looks also promising

**Comment by prolic** [comment]
What about https://github.com/webmozart/json? Didn't you recommend it before? What's better?

**Comment by codeliner** [comment]
Not sure about the current version of webmozart/json but we use an older version of it. It works great but the version we use only takes json strings for both the schema and the data. I came across JSON Guard today while searching Flysystem (also a league package) and read the readme. The example shows that it works with php objects so you don't need a json string. Unfortunately, it does not work with PHP arrays so still not perfect for command payload validation :(

but userland decision anyway ;)

**Comment by prolic** [comment]
just found this one: https://github.com/serkin/volan - but didn't look much in it yet

**Comment by codeliner** [comment]
Unfortunately not json schema

**Comment by prolic** [comment]
We leave that up to the user how to validate commands.
