### ISSUE TITLE
Consider Serverless Event Gateway

### ISSUE THREAD

**Issue by codeliner** [prooph/micro#48]
https://github.com/serverless/event-gateway

Looks like micro and event gateway would play very nice together.

**Comment by codeliner** [comment]
Serverless abstraction for PHP: https://github.com/mnapoli/bref

**Comment by prolic** [comment]
This should be extra packages on top of micro. I'm working on integration of this with the non-blocking http server from amphp at the moment. I'm not sure yet, if this will be a separate package, or simply a blog post explaining those concepts.
