### ISSUE TITLE
Input and output streams can differ

### ISSUE THREAD

**Issue by codeliner** [prooph/micro#5]
I often use the concept that one aggregate starts the lifecycle of another aggregate.

We have such an example in prooph-do: https://github.com/prooph/proophessor-do/blob/master/src/Model/Todo/Handler/PostTodoHandler.php#L57

user aggregate handles `PostTodo` command and a new todo aggregate is born.
How can we handle this without a dedicated command handler, configure "read from stream" and "write to stream" separately?

**Comment by prolic** [comment]
Do we take the route of process managers? If so, this can be closed!

**Comment by codeliner** [comment]
yes, seems to be the best option.
